'use client';
import React from 'react';
import { useActiveLinkOnScroll } from '@/hooks/useActiveLinkOnScroll';

const ContactSection = () => {
    const { activeLink, navigateTo } = useActiveLinkOnScroll(['contacto']);

    return (
        <section id="contacto" title="Contacto" className={"my-5"}>
            <h1 className={"text-4xl mb-4"}>Contacto</h1>
            Lorem ipsum dolor sit amet, consectetur adipisicing elit. Aliquid aut consequuntur culpa deserunt enim, error itaque magnam maiores minima minus molestias nihil perferendis quibusdam recusandae, saepe tempora totam ullam voluptatum? Lorem ipsum dolor sit amet, consectetur adipisicing elit. Aspernatur eius error, excepturi, harum ipsam labore laborum libero mollitia, nisi odio praesentium quas quod ratione repellat sit. Nesciunt optio rerum temporibus. Lorem ipsum dolor sit amet, consectetur adipisicing elit. Asperiores beatae deserunt exercitationem nam officia quisquam quo sit vitae voluptate voluptates. Explicabo numquam vitae voluptas voluptates. Asperiores blanditiis soluta ut voluptatum.
            Lorem ipsum dolor sit amet, consectetur adipisicing elit. Dolore necessitatibus officia repudiandae. Adipisci cumque cupiditate, distinctio dolorem in ipsa minima, modi molestiae necessitatibus odit perspiciatis, quis repudiandae sequi sint veritatis!
            Lorem ipsum dolor sit amet, consectetur adipisicing elit. Aliquid aut consequuntur culpa deserunt enim, error itaque magnam maiores minima minus molestias nihil perferendis quibusdam recusandae, saepe tempora totam ullam voluptatum? Lorem ipsum dolor sit amet, consectetur adipisicing elit. Aspernatur eius error, excepturi, harum ipsam labore laborum libero mollitia, nisi odio praesentium quas quod ratione repellat sit. Nesciunt optio rerum temporibus. Lorem ipsum dolor sit amet, consectetur adipisicing elit. Asperiores beatae deserunt exercitationem nam officia quisquam quo sit vitae voluptate voluptates. Explicabo numquam vitae voluptas voluptates. Asperiores blanditiis soluta ut voluptatum.
            Lorem ipsum dolor sit amet, consectetur adipisicing elit. Dolore necessitatibus officia repudiandae. Adipisci cumque cupiditate, distinctio dolorem in ipsa minima, modi molestiae necessitatibus odit perspiciatis, quis repudiandae sequi sint veritatis!
            Lorem ipsum dolor sit amet, consectetur adipisicing elit. Aliquid aut consequuntur culpa deserunt enim, error itaque magnam maiores minima minus molestias nihil perferendis quibusdam recusandae, saepe tempora totam ullam voluptatum? Lorem ipsum dolor sit amet, consectetur adipisicing elit. Aspernatur eius error, excepturi, harum ipsam labore laborum libero mollitia, nisi odio praesentium quas quod ratione repellat sit. Nesciunt optio rerum temporibus. Lorem ipsum dolor sit amet, consectetur adipisicing elit. Asperiores beatae deserunt exercitationem nam officia quisquam quo sit vitae voluptate voluptates. Explicabo numquam vitae voluptas voluptates. Asperiores blanditiis soluta ut voluptatum.
            Lorem ipsum dolor sit amet, consectetur adipisicing elit. Dolore necessitatibus officia repudiandae. Adipisci cumque cupiditate, distinctio dolorem in ipsa minima, modi molestiae necessitatibus odit perspiciatis, quis repudiandae sequi sint veritatis!
            Lorem ipsum dolor sit amet, consectetur adipisicing elit. Aliquid aut consequuntur culpa deserunt enim, error itaque magnam maiores minima minus molestias nihil perferendis quibusdam recusandae, saepe tempora totam ullam voluptatum? Lorem ipsum dolor sit amet, consectetur adipisicing elit. Aspernatur eius error, excepturi, harum ipsam labore laborum libero mollitia, nisi odio praesentium quas quod ratione repellat sit. Nesciunt optio rerum temporibus. Lorem ipsum dolor sit amet, consectetur adipisicing elit. Asperiores beatae deserunt exercitationem nam officia quisquam quo sit vitae voluptate voluptates. Explicabo numquam vitae voluptas voluptates. Asperiores blanditiis soluta ut voluptatum.
            Lorem ipsum dolor sit amet, consectetur adipisicing elit. Dolore necessitatibus officia repudiandae. Adipisci cumque cupiditate, distinctio dolorem in ipsa minima, modi molestiae necessitatibus odit perspiciatis, quis repudiandae sequi sint veritatis!
            Lorem ipsum dolor sit amet, consectetur adipisicing elit. Aliquid aut consequuntur culpa deserunt enim, error itaque magnam maiores minima minus molestias nihil perferendis quibusdam recusandae, saepe tempora totam ullam voluptatum? Lorem ipsum dolor sit amet, consectetur adipisicing elit. Aspernatur eius error, excepturi, harum ipsam labore laborum libero mollitia, nisi odio praesentium quas quod ratione repellat sit. Nesciunt optio rerum temporibus. Lorem ipsum dolor sit amet, consectetur adipisicing elit. Asperiores beatae deserunt exercitationem nam officia quisquam quo sit vitae voluptate voluptates. Explicabo numquam vitae voluptas voluptates. Asperiores blanditiis soluta ut voluptatum.
            Lorem ipsum dolor sit amet, consectetur adipisicing elit. Dolore necessitatibus officia repudiandae. Adipisci cumque cupiditate, distinctio dolorem in ipsa minima, modi molestiae necessitatibus odit perspiciatis, quis repudiandae sequi sint veritatis!
        </section>
    );
}

export default ContactSection;